"""
This type stub file was generated by pyright.
"""

def connect_all(state):
    '''
    Connect to all the configured servers in parallel. Reads/writes state.inventory.

    Args:
        state (``pyinfra.api.State`` obj): the state containing an inventory to connect to
    '''
    ...

def disconnect_all(state):
    ...

