"""
This type stub file was generated by pyright.
"""

import six
from gevent.lock import BoundedSemaphore
from typing import Any, Optional

'''
The pyinfra facts API. Facts enable pyinfra to collect remote server state which
is used to "diff" with the desired state, producing the final commands required
for a deploy.
'''
FACTS = {  }
FACT_LOCK = BoundedSemaphore()
def is_fact(name):
    ...

def get_fact_class(name):
    ...

def get_fact_names():
    '''
    Returns a list of available facts in camel_case format.
    '''
    ...

class FactMeta(type):
    '''
    Metaclass to dynamically build the facts index.
    '''
    def __init__(cls, name, bases, attrs):
        ...
    


@six.add_metaclass(FactMeta)
class FactBase(object):
    abstract = ...
    shell_executable = ...
    @staticmethod
    def default():
        '''
        Set the default attribute to be a type (eg list/dict).
        '''
        ...
    
    @staticmethod
    def process(output):
        ...
    
    def process_pipeline(self, args, output):
        ...
    


@six.add_metaclass(FactMeta)
class ShortFactBase(object):
    fact = ...


def get_short_facts(state, short_fact, **kwargs):
    ...

def get_facts(state, name, args: Optional[Any] = ..., ensure_hosts: Optional[Any] = ...):
    '''
    Get a single fact for all hosts in the state.
    '''
    ...

def get_fact(state, host, name):
    '''
    Wrapper around ``get_facts`` returning facts for one host or a function
    that does.
    '''
    ...

