"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def extract_name_data(names):
    ...

class Inventory(object):
    '''
    Represents a collection of target hosts. Stores and provides access to group data,
    host data and default data for these hosts.

    Args:
        names_data: tuple of ``(names, data)``
        ssh_user: override SSH user
        ssh_port: override SSH port
        ssh_key: override SSH key filename
        ssh_key_password: override password for the SSH key
        ssh_password: override SSH password
        winrm_username: override WINRM username
        winrm_password: override WINRM pasword
        winrm_port: override WINRM port
        **groups: map of group names -> ``(names, data)``
    '''
    state = ...
    def __init__(self, names_data, ssh_user: Optional[Any] = ..., ssh_port: Optional[Any] = ..., ssh_key: Optional[Any] = ..., ssh_key_password: Optional[Any] = ..., ssh_password: Optional[Any] = ..., winrm_username: Optional[Any] = ..., winrm_password: Optional[Any] = ..., winrm_port: Optional[Any] = ..., **groups):
        self.groups = ...
        self.host_data = ...
        self.group_data = ...
        self.override_data = ...
        self.data = ...
        self.hosts = ...
    
    def make_hosts_and_groups(self, names, groups):
        ...
    
    def __getitem__(self, key):
        '''
        DEPRECATED: please use ``Inventory.get_host`` instead.
        '''
        ...
    
    def __getattr__(self, key):
        '''
        DEPRECATED: please use ``Inventory.get_group`` instead.
        '''
        ...
    
    def __len__(self):
        '''
        Returns the number of active inventory hosts.
        '''
        ...
    
    def __iter__(self):
        '''
        Iterates over active inventory hosts.
        '''
        ...
    
    def len_all_hosts(self):
        '''
        Returns the number of hosts in the inventory, active or not.
        '''
        ...
    
    def iter_all_hosts(self):
        '''
        Iterates over all inventory hosts, active or not.
        '''
        ...
    
    def get_host(self, name, default=...):
        '''
        Get a single host by name.
        '''
        ...
    
    def get_group(self, name, default=...):
        '''
        Get a list of hosts belonging to a group.
        '''
        ...
    
    def get_data(self):
        '''
        Get the base/all data attached to this inventory.
        '''
        ...
    
    def get_override_data(self):
        '''
        Get override data for this inventory.
        '''
        ...
    
    def get_host_data(self, hostname):
        '''
        Get data for a single host in this inventory.
        '''
        ...
    
    def get_group_data(self, group):
        '''
        Get data for a single group in this inventory.
        '''
        ...
    
    def get_groups_data(self, groups):
        '''
        Gets aggregated data from a list of groups. Vars are collected in order so, for
        any groups which define the same var twice, the last group's value will hold.
        '''
        ...
    
    def get_deploy_data(self):
        '''
        Gets any default data attached to the current deploy, if any.
        '''
        ...
    


