"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def _run_server_op(state, host, op_hash):
    ...

def _run_server_ops(state, host, progress: Optional[Any] = ...):
    '''
    Run all ops for a single server.
    '''
    ...

def _run_serial_ops(state):
    '''
    Run all ops for all servers, one server at a time.
    '''
    ...

def _run_no_wait_ops(state):
    '''
    Run all ops for all servers at once.
    '''
    ...

def _run_single_op(state, op_hash):
    '''
    Run a single operation for all servers. Can be configured to run in serial.
    '''
    ...

def run_ops(state, serial: bool = ..., no_wait: bool = ...):
    '''
    Runs all operations across all servers in a configurable manner.

    Args:
        state (``pyinfra.api.State`` obj): the deploy state to execute
        serial (boolean): whether to run operations host by host
        no_wait (boolean): whether to wait for all hosts between operations
    '''
    ...

