"""
This type stub file was generated by pyright.
"""

from pyinfra.api import FactBase
from typing import Any, Optional

def make_psql_command(database: Optional[Any] = ..., user: Optional[Any] = ..., password: Optional[Any] = ..., host: Optional[Any] = ..., port: Optional[Any] = ..., executable=...):
    ...

def make_execute_psql_command(command, **postgresql_kwargs):
    ...

class PostgresqlFactBase(FactBase):
    abstract = ...
    def command(self, postgresql_user: Optional[Any] = ..., postgresql_password: Optional[Any] = ..., postgresql_host: Optional[Any] = ..., postgresql_port: Optional[Any] = ...):
        ...
    


class PostgresqlRoles(PostgresqlFactBase):
    '''
    Returns a dict of PostgreSQL roles and data:

    .. code:: python

        'pyinfra': {
            'super': true,
            'createrole': false,
            'createdb': false,
            ...
        },
        ...
    '''
    default = ...
    postgresql_command = ...
    def process(self, output):
        ...
    


class PostgresqlDatabases(PostgresqlFactBase):
    '''
    Returns a dict of PostgreSQL databases and metadata:

    .. code:: python

        "pyinfra_stuff": {
            "encoding": "UTF8",
            "collate": "en_US.UTF-8",
            "ctype": "en_US.UTF-8",
            ...
        },
        ...
    '''
    default = ...
    postgresql_command = ...
    def process(self, output):
        ...
    


