"""
This type stub file was generated by pyright.
"""

import platform
import sys
from collections import deque
from contextlib import contextmanager
from typing import Any, Optional

IS_WINDOWS = platform.system() == 'Windows'
WAIT_TIME = 1 / 5
WAIT_CHARS = deque(('-', '/', '|', '\\'))
IS_TTY = sys.stdout.isatty() and sys.stderr.isatty()
TERMINAL_WIDTH = 0
if IS_TTY:
    ...
def _print_spinner(stop_event, progress_queue):
    ...

@contextmanager
def progress_spinner(items, prefix_message: Optional[Any] = ...):
    ...

