"""
This type stub file was generated by pyright.
"""

'''
These three pseudo modules (state, inventory, host) are used throughout pyinfra
and provide the magic that means "from pyinfra import host" inside a deploy
file always represents the *current* host being executed, ie these modules are
dynamic and change during execution of pyinfra.

Although CLI only when in use, these are bundled into the main pyinfra package
as they are utilised throughout (to determine the current state/host when
executing in CLI mode).
'''
class PseudoModule(object):
    _module = ...
    def __getattr__(self, key):
        ...
    
    def __setattr__(self, key, value):
        ...
    
    def __getitem__(self, key):
        ...
    
    def __iter__(self):
        ...
    
    def __len__(self):
        ...
    
    def __eq__(self, other):
        ...
    
    def set(self, module):
        ...
    
    def reset(self):
        ...
    
    def isset(self):
        ...
    


