"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage apk packages.
'''
@operation
def upgrade(state, host):
    '''
    Upgrades all apk packages.
    '''
    ...

_upgrade = upgrade
@operation
def update(state, host):
    '''
    Updates apk repositories.
    '''
    ...

_update = update
@operation
def packages(state, host, packages: Optional[Any] = ..., present: bool = ..., latest: bool = ..., update: bool = ..., upgrade: bool = ...):
    '''
    Add/remove/update apk packages.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + latest: whether to upgrade packages without a specified version
    + update: run apk update before installing packages
    + upgrade: run apk upgrade before installing packages

    Versions:
        Package versions can be pinned like apk: ``<pkg>=<version>``.

    Examples:

    .. code:: python

        # Update package list and install packages
        apk.packages(
            {'Install Asterisk and Vim'},
            ['asterisk', 'vim'],
            update=True,
        )

        # Install the latest versions of packages (always check)
        apk.packages(
            {'Install latest Vim'},
            ['vim'],
            latest=True,
        )
    '''
    ...

