"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage brew packages on mac/OSX. See https://brew.sh/
'''
@operation
def update(state, host):
    '''
    Updates brew repositories.
    '''
    ...

_update = update
@operation
def upgrade(state, host):
    '''
    Upgrades all brew packages.
    '''
    ...

_upgrade = upgrade
@operation
def packages(state, host, packages: Optional[Any] = ..., present: bool = ..., latest: bool = ..., update: bool = ..., upgrade: bool = ...):
    '''
    Add/remove/update brew packages.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + latest: whether to upgrade packages without a specified version
    + update: run brew update before installing packages
    + upgrade: run brew upgrade before installing packages

    Versions:
        Package versions can be pinned like brew: ``<pkg>@<version>``.

    Examples:

    .. code:: python

        # Update package list and install packages
        brew.packages(
            {'Install Vim and vimpager'},
            ['vimpager', 'vim'],
            update=True,
        )

        # Install the latest versions of packages (always check)
        brew.packages(
            {'Install latest Vim'},
            ['vim'],
            latest=True,
        )
    '''
    ...

@operation
def cask_upgrade(state, host):
    '''
    Upgrades all brew casks.
    '''
    ...

@operation
def casks(state, host, packages: Optional[Any] = ..., present: bool = ..., latest: bool = ..., upgrade: bool = ...):
    '''
    Add/remove/update brew casks.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + latest: whether to upgrade packages without a specified version
    + upgrade: run brew cask upgrade before installing packages

    Versions:
        Package versions can be pinned like brew: ``<pkg>@<version>``.

    Example:

    .. code:: python

        brew.casks(
            {'Upgrade and install the latest package via casks'},
            ['godot'],
            upgrade=True,
            latest=True,
        )

    '''
    ...

@operation
def tap(state, host, name, present: bool = ...):
    '''
    Add/remove brew taps.

    + name: the name of the tasp
    + present: whether this tap should be present or not

    Examples:

    .. code:: python

        brew.tap(
            {'Add a brew tap'},
            'includeos/includeos',
        )

        # multiple taps
        taps = ['includeos/includeos', 'ktr0731/evans']
        for tap in taps:
            brew.tap(
                {f'Add brew tap {tap}'},
                tap,
            )

    '''
    ...

