"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage git repositories and configuration.
'''
@operation(pipeline_facts={ 'git_config': 'repo' })
def config(state, host, key, value, repo: Optional[Any] = ...):
    '''
    Manage git config for a repository or globally.

    + key: the key of the config to ensure
    + value: the value this key should have
    + repo: specify the git repo path to edit local config (defaults to global)

    Example:

    .. code:: python

        git.config(
            {'Ensure user name is set for a repo'},
            key='user.name',
            value='Anon E. Mouse',
            repo='/usr/local/src/pyinfra',
        )

    '''
    ...

@operation(pipeline_facts={ 'git_branch': 'target' })
def repo(state, host, source, target, branch=..., pull: bool = ..., rebase: bool = ..., user: Optional[Any] = ..., group: Optional[Any] = ..., use_ssh_user: bool = ..., ssh_keyscan: bool = ..., update_submodules: bool = ..., recursive_submodules: bool = ...):
    '''
    Clone/pull git repositories.

    + source: the git source URL
    + target: target directory to clone to
    + branch: branch to pull/checkout
    + pull: pull any changes for the branch
    + rebase: when pulling, use ``--rebase``
    + user: chown files to this user after
    + group: chown files to this group after
    + ssh_keyscan: keyscan the remote host if not in known_hosts before clone/pull
    + update_submodules: update any git submodules
    + recursive_submodules: update git submodules recursively

    + [DEPRECATED] use_ssh_user: whether to use the SSH user to clone/pull

    SSH user (deprecated, please use ``preserve_sudo_env``):
        This is an old hack from pyinfra <0.4 which did not support the global
        kwarg ``preserve_sudo_env``. It does the following:

        * makes the target directory writeable by all
        * clones/pulls w/o sudo as the connecting SSH user
        * removes other/group write permissions - unless group is defined, in
          which case only other

    Example:

    .. code:: python

        git.repo(
            {'Clone repo'},
            'https://github.com/Fizzadar/pyinfra.git',
            '/usr/local/src/pyinfra',
        )
    '''
    ...

