"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation

'''
The LXD modules manage LXD containers
'''
def get_container_named(name, containers):
    ...

@operation
def container(state, host, name, present: bool = ..., image=...):
    '''
    Add/remove LXD containers.

    Note: does not check if an existing container is based on the specified
    image.

    + name: name of the container
    + image: image to base the container on
    + present: whether the container should be present or absent

    Example:

    .. code:: python

        lxd.container(
            {'Add an ubuntu container'},
            'ubuntu19',
            image='ubuntu:19.10',
        )
    '''
    ...

