"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage npm (aka node aka Node.js) packages.
'''
@operation
def packages(state, host, packages: Optional[Any] = ..., present: bool = ..., latest: bool = ..., directory: Optional[Any] = ...):
    '''
    Install/remove/update npm packages.

    + packages: list of packages to ensure
    + present: whether the packages should be present
    + latest: whether to upgrade packages without a specified version
    + directory: directory to manage packages for, defaults to global

    Versions:
        Package versions can be pinned like npm: ``<pkg>@<version>``.
    '''
    ...

