"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage pacman packages. (Arch Linux package manager)
'''
@operation
def upgrade(state, host):
    '''
    Upgrades all pacman packages.
    '''
    ...

_upgrade = upgrade
@operation
def update(state, host):
    '''
    Updates pacman repositories.
    '''
    ...

_update = update
@operation
def packages(state, host, packages: Optional[Any] = ..., present: bool = ..., update: bool = ..., upgrade: bool = ...):
    '''
    Add/remove pacman packages.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + update: run pacman -Sy before installing packages
    + upgrade: run pacman -Syu before installing packages

    Versions:
        Package versions can be pinned like pacman: ``<pkg>=<version>``.

    Example:

    .. code:: python

        pacman.packages(
            {'Install Vim and a plugin'},
            ['vim-fugitive', 'vim'],
            update=True,
        )
    '''
    ...

