"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage BSD packages and repositories. Note that BSD package names are case-sensitive.
'''
@operation
def packages(state, host, packages: Optional[Any] = ..., present: bool = ..., pkg_path: Optional[Any] = ...):
    '''
    Install/remove/update pkg_* packages.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + pkg_path: the PKG_PATH environment variable to set

    pkg_path:
        By default this is autogenerated as follows (tested/working for OpenBSD):
        ``http://ftp.<OS>.org/pub/<OS>/<VERSION>/packages/<ARCH>/``. Note that OpenBSD's
        official mirrors only hold the latest two versions packages.

        NetBSD/FreeBSD helpfully use their own directory structures, so the default won't
        work.

    Example:

    .. code:: python

        pkg.packages(
            {'Install Vim and Vim Addon Manager'},
            ['vim-addon-manager', 'vim'],
        )

    '''
    ...

