"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation
from typing import Any, Optional

'''
Manage OpenVZ containers with ``vzctl``.
'''
@operation
def start(state, host, ctid, force: bool = ...):
    '''
    Start OpenVZ containers.

    + ctid: CTID of the container to start
    + force: whether to force container start
    '''
    ...

@operation
def stop(state, host, ctid):
    '''
    Stop OpenVZ containers.

    + ctid: CTID of the container to stop
    '''
    ...

@operation
def restart(state, host, ctid, force: bool = ...):
    '''
    Restart OpenVZ containers.

    + ctid: CTID of the container to restart
    + force: whether to force container start
    '''
    ...

@operation
def mount(state, host, ctid):
    '''
    Mount OpenVZ container filesystems.

    + ctid: CTID of the container to mount
    '''
    ...

@operation
def unmount(state, host, ctid):
    '''
    Unmount OpenVZ container filesystems.

    + ctid: CTID of the container to unmount
    '''
    ...

@operation
def delete(state, host, ctid):
    '''
    Delete OpenVZ containers.

    + ctid: CTID of the container to delete
    '''
    ...

@operation
def create(state, host, ctid, template: Optional[Any] = ...):
    '''
    Create OpenVZ containers.

    + ctid: CTID of the container to create
    '''
    ...

@operation
def set(state, host, ctid, save: bool = ..., **settings):
    '''
    Set OpenVZ container details.

    + ctid: CTID of the container to set
    + save: whether to save the changes
    + settings: settings/arguments to apply to the container

    Settings/arguments:
        these are mapped directly to ``vztctl`` arguments, eg
        ``hostname='my-host.net'`` becomes ``--hostname my-host.net``.
    '''
    ...

