"""
This type stub file was generated by pyright.
"""

from pyinfra.api import operation

'''
The windows module handles misc windows operations.
'''
@operation
def service(state, host, name, running: bool = ..., restart: bool = ..., suspend: bool = ...):
    '''
    Stop/Start a Windows service.

    + name: name of the service to manage
    + running: whether the the service should be running or stopped
    + restart: whether the the service should be restarted
    + suspend: whether the the service should be suspended

    Example:

    .. code:: python

        windows.service(
            {'Stop the spooler service'},
            'service',
            running=False,
        )
    '''
    ...

@operation
def reboot(state, host):
    '''
    Restart the server.
    '''
    ...

