"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def _remove_prefix(title, remove_prefix):
    ...

def parse_columns_and_rows(lines, delimiter, remove_column_prefix: Optional[Any] = ..., title_parser: Optional[Any] = ...):
    ...

