"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def ensure_mode_int(mode):
    ...

def sed_replace(filename, line, replace, flags: Optional[Any] = ...):
    ...

def chmod(target, mode, recursive: bool = ...):
    ...

def chown(target, user, group: Optional[Any] = ..., recursive: bool = ..., dereference: bool = ...):
    ...

