"""
This type stub file was generated by pyright.
"""

from pyinfra.api.util import memoize
from typing import Any, Optional

@memoize
def show_warning():
    ...

@memoize
def get_ansible_inventory(inventory_filename: Optional[Any] = ...):
    ...

def _parse_ansible_hosts(hosts):
    ...

def make_names_data(inventory_filename: Optional[Any] = ...):
    ...

