"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def make_names_data(hostname: Optional[Any] = ...):
    ...

def connect(state, host):
    ...

def run_shell_command(state, host, command, get_pty: bool = ..., timeout: Optional[Any] = ..., stdin: Optional[Any] = ..., success_exit_codes: Optional[Any] = ..., print_output: bool = ..., print_input: bool = ..., return_combined_output: bool = ..., **command_kwargs):
    '''
    Execute a command on the local machine.

    Args:
        state (``pyinfra.api.State`` object): state object for this command
        host (``pyinfra.api.Host`` object): the target host
        command (string): actual command to execute
        sudo (boolean): whether to wrap the command with sudo
        sudo_user (string): user to sudo to
        env (dict): envrionment variables to set
        timeout (int): timeout for this command to complete before erroring

    Returns:
        tuple: (exit_code, stdout, stderr)
        stdout and stderr are both lists of strings from each buffer.
    '''
    ...

def put_file(state, host, filename_or_io, remote_filename, print_output: bool = ..., print_input: bool = ..., **command_kwargs):
    '''
    Upload a local file or IO object by copying it to a temporary directory
    and then writing it to the upload location.
    '''
    ...

def get_file(state, host, remote_filename, filename_or_io, print_output: bool = ..., print_input: bool = ..., **command_kwargs):
    '''
    Download a local file by copying it to a temporary location and then writing
    it to our filename or IO object.
    '''
    ...

