"""
This type stub file was generated by pyright.
"""

from pyinfra.api.util import memoize
from typing import Any, Optional

def _get_mech_ssh_config(queue, progress, target):
    ...

@memoize
def get_mech_config(limit: Optional[Any] = ...):
    ...

@memoize
def get_mech_options():
    ...

def _make_name_data(host):
    ...

def make_names_data(limit: Optional[Any] = ...):
    ...

