"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def run_local_process(command, stdin: Optional[Any] = ..., timeout: Optional[Any] = ..., print_output: bool = ..., print_prefix: Optional[Any] = ...):
    ...

def read_buffers_into_queue(stdout_buffer, stderr_buffer, timeout, print_output, print_prefix):
    ...

def split_combined_output(combined_output):
    ...

def write_stdin(stdin, buffer):
    ...

def make_unix_command(command, env: Optional[Any] = ..., su_user=..., use_su_login=..., sudo=..., sudo_user=..., use_sudo_login=..., preserve_sudo_env=..., shell_executable=...):
    '''
    Builds a shell command with various kwargs.
    '''
    ...

def make_win_command(command, env: Optional[Any] = ..., shell_executable=...):
    '''
    Builds a windows command with various kwargs.
    '''
    ...

