"""
This type stub file was generated by pyright.
"""

from paramiko import SSHClient as ParamikoClient
from pyinfra.api.util import memoize

'''
This file as originally part of the "sshuserclient" pypi package. The GitHub
source has now vanished (https://github.com/tobald/sshuserclient).
'''
@memoize
def get_ssh_config():
    ...

class SSHClient(ParamikoClient):
    '''
    An SSHClient which honors ssh_config and supports proxyjumping
    original idea at http://bitprophet.org/blog/2012/11/05/gateway-solutions/
    '''
    def connect(self, hostname, **kwargs):
        ...
    
    def gateway(self, target, target_port):
        ...
    
    def parse_config(self, hostname):
        ...
    
    def derive_shorthand(self, host_string):
        ...
    


