"""
This type stub file was generated by pyright.
"""

from paramiko import SSHConfig as ParamikoSSHConfig
from typing import Any, Optional

'''
This file as originally part of the "sshuserclient" pypi package. The GitHub
source has now vanished (https://github.com/tobald/sshuserclient).
'''
class SSHConfig(ParamikoSSHConfig):
    '''
    an SSHConfig that supports includes directives
    https://github.com/paramiko/paramiko/pull/1194
    '''
    SETTINGS_REGEX = ...
    def parse(self, file_obj, parsed_files: Optional[Any] = ...):
        '''
        Read an OpenSSH config from the given file object.

        :param file_obj: a file-like object to read the config file from
        '''
        ...
    


